@eCommerceServer_HostAddress = http://localhost:5191

POST http://localhost:5191/api/Auth/Login
Accept: application/json
Content-Type: application/json

{
  "email": "string@string.com",
  "password": "String123"
}
###

